travis:
  secure:
    BINSTAR_TOKEN: Ji5KD+2OjhQ6sFgqkkCyQ4F/6bMQBaXhtn8FkH/auq6yI+rlhJjoC6UjMo75oUXRj9Lhl7sE+y7aVGXig8u0EWPX4AUpeL9J/4BJgkIXKNE0V7Q2mBPedSkb9gEAe5QFy0fwfzoMN2NFBozoF+uIsv5/Y8mybtHnErkbQjDo0RvtyMt4tKljRlESnb/KhbZz71Fs+zfDjsJrE6P+MzEYzMHtJbfC4axXNAhlR7l9QBnnWXY12ZZeL5h14vigP2/eT4GMFB0CLx5r2ITcfbyY4W/M1bMTGAyJlkjgVQ5g8mHVtipzELOmkX0nZsAWkRrJAhwQxqvAcYG6bhcNrlmYLeZm7jssBUm2zEMuZOSW+2iaYQdK3J2PyPl0y3z89h8QdnOF8c38FuLeUivskrYM9vCO3aPh0HL7ACsVtYHBq2SqAE9Eny0TjROJ3oPXHdsrtTB1bSAFTulvf2lq2qFwQND9QujRhpFIy+1Vi3f9KuJlfotOp6WCUUP0GKNUkKwvK0BSfgeDX6MQgnOfIMjJ4/PkioATIPrd+n3OtdotLJ/Y/kZqqIYJrtHSfAANVOmQ4dyGJ3OT7oxG7FRXXs5frk0h8NCyAwIsgMhmiMyA0PReWy/hx+K2KuJqylNjW/2uqCjGO8J3nLLWqAHrPsZdqmrPbq+1KPtDhWuPFrAjhfg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
